# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      Commit:
        description: 'e.g. bf819e2...yadayada...f35ede9'
        required: true
      Site:
        description: '___________.azurewebsites.net'
        required: true
      SiteConfirm:
        description: '___________.azurewebsites.net (confirm)'
        required: true

jobs:
  validate-inputs:
    runs-on: windows-latest
    steps:
      - run: "echo Commit: ${{ github.event.inputs.Commit }}" 
      - run: "echo Site: ${{ github.event.inputs.Site }}"
      - run: "echo SiteConfirm: ${{ github.event.inputs.SiteConfirm }}"
      - run: exit 1
        name: Halt if Site and SiteConfirm differ
        if: github.event.inputs.Site != github.event.inputs.SiteConfirm
    
  deploy:
    needs: [validate-inputs]
    runs-on: windows-latest

    steps:
    - name: Get Source
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.inputs.Commit }}
        
    - name: Add Version Comment
      uses: DamianReeves/write-file-action
      with:
        path: src/SDCode.Web/Views/Home/Index.cshtml
        contents: echo "<!-- built from https://github.com/evmadden/SDCexp1/commit/${{ github.event.inputs.Commit }} -->"
        write-mode: append

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build --configuration Release src\SDCode.Web

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp src\SDCode.Web

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.Site }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77d137eb06fc4b819d24d148b3622329 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
